### Author : Riasad Alvi
### Date   : 21 March 2025

A **tensor** in PyTorch is a multi-dimensional array, similar to a NumPy array, but with additional capabilities for GPU acceleration and support for automatic differentiation (gradients).

### Key Points:
1. **Multi-dimensional**: Tensors can have any number of dimensions (e.g., scalar, vector, matrix, or higher-dimensional arrays).
2. **GPU Support**: Tensors can be moved to a GPU for faster computations.
3. **Automatic Differentiation**: Tensors support gradients, allowing easy calculation of derivatives for optimization in machine learning.

### Why We Need Tensors:
- **Efficient Computation**: Tensors allow efficient mathematical operations on large datasets, especially with GPU support.
- **Machine Learning**: They are the fundamental data structure in neural networks for holding inputs, weights, and gradients.

In [1]:
import torch

## Creating a Tensor

In [10]:
# empty() creates a tensor of uninitialized values.

a = torch.empty(2, 3)

# Example:
# Creates a tensor of shape (2, 3) with random, uninitialized values.
# The values inside are not zero and are unpredictable.

print(a)

tensor([[2.8684e-36, 0.0000e+00, 0.0000e+00],
        [7.0417e-34, 0.0000e+00, 0.0000e+00]])


In [11]:
# check type
type(a)

torch.Tensor

In [12]:
# zeros() creates a tensor filled with zeros.

# Creating a tensor of shape (2, 3) filled with zeros
a = torch.zeros(2, 3)

# Example:
# Creates a tensor of shape (2, 3) where all values are 0.

print(a)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# ones() creates a tensor filled with ones.

# Creating a tensor of shape (2, 3) filled with ones
a = torch.ones(2, 3)

# Example:
# Creates a tensor of shape (2, 3) where all values are 1.

print(a)


tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
# rand() creates a tensor filled with random values between 0 and 1.

# Creating a tensor of shape (2, 3) with random values
a = torch.rand(2, 3)

# Example:
# Creates a tensor of shape (2, 3) where values are randomly sampled from a uniform distribution between 0 and 1.

print(a)


tensor([[0.4226, 0.1308, 0.9461],
        [0.3849, 0.7780, 0.4698]])


In [15]:
torch.rand(2,3)

tensor([[0.3977, 0.8352, 0.7334],
        [0.6700, 0.8025, 0.6209]])

### Each time rand values will be different , but if we want random values once and use same value multiple times, then we need to use manual_seed:

In [16]:
# manual_seed() sets the seed for random number generation to ensure reproducibility.

# Setting the seed for random number generation
torch.manual_seed(100)

# Creating a tensor of shape (2, 3) with random values
a = torch.rand(2, 3)

# Example:
# By setting the seed, the random values generated will be the same every time the code is run.

print(a)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [17]:
# tensor() creates a tensor from a Python list or array.

# Creating a tensor from a 2x3 list
a = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Example:
# Converts a Python list into a tensor with shape (2, 3).

print(a)


tensor([[1, 2, 3],
        [4, 5, 6]])


In [18]:
# arange() creates a tensor with values in a specified range with a given step.

print("using arange ->", torch.arange(0, 10, 2))  # tensor([0, 2, 4, 6, 8])

# linspace() creates a tensor with evenly spaced values over a specified interval.

print("using linspace ->", torch.linspace(0, 10, 10))  # tensor([ 0.,  1.25,  2.5, ..., 10.])

# eye() creates an identity matrix of a given size.

print("using eye ->", torch.eye(5))  # 5x5 identity matrix

# full() creates a tensor filled with a specified value.

print("using full ->", torch.full((3, 3), 5))  # tensor([[5, 5, 5], [5, 5, 5], [5, 5, 5]])


using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [19]:
# Creating a tensor from a 2x3 list
x = torch.tensor([[2, 3, 4], [5, 6, 7]])

# Example:
# Creates a tensor of shape (2, 3) with the given values.

print(x)


tensor([[2, 3, 4],
        [5, 6, 7]])


In [20]:
x.shape

torch.Size([2, 3])

In [21]:
# empty_like() creates a tensor with the same shape and type as the input tensor, but with uninitialized values.

# Creating a tensor x
x = torch.tensor([[2, 3, 4], [5, 6, 7]])

# Using empty_like() to create a tensor of the same size and type as x, with random uninitialized values
y = torch.empty_like(x)

print(y)


tensor([[      168442736, 134290793225488, 134290793283728],
        [      170401296, 134290793234128, 134290791720704]])


In [22]:
# zeros_like() creates a tensor with the same shape and type as the input tensor, but filled with zeros.

# Creating a tensor x
x = torch.tensor([[2, 3, 4], [5, 6, 7]])

# Using zeros_like() to create a tensor of the same size and type as x, filled with zeros
y = torch.zeros_like(x)

print(y)


tensor([[0, 0, 0],
        [0, 0, 0]])


In [23]:
# ones_like() creates a tensor with the same shape and type as the input tensor, but filled with ones.

# Creating a tensor x
x = torch.tensor([[2, 3, 4], [5, 6, 7]])

# Using ones_like() to create a tensor of the same size and type as x, filled with ones
y = torch.ones_like(x)

print(y)


tensor([[1, 1, 1],
        [1, 1, 1]])


In [24]:
# rand_like() creates a tensor with the same shape and type as the input tensor, filled with random values between 0 and 1.
# dtype=torch.float32 is specified because rand_like generates values in float32 by default.

# Creating a tensor x
x = torch.tensor([[2, 3, 4], [5, 6, 7]])

# Using rand_like() to create a tensor of the same size as x with random float32 values
y = torch.rand_like(x, dtype=torch.float32)

print(y)


tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


## Tensor Data Types

In [25]:
# find data type
x.dtype

torch.int64

In [26]:
# Creating a tensor with specified data type (int32)

# Using tensor() with dtype=torch.int32 to create a tensor of integers
x = torch.tensor([7.9, 8.99, 3.6], dtype=torch.int32)

print(x)

tensor([7, 8, 3], dtype=torch.int32)


In [27]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [29]:
# to() is used to cast a tensor to a specified data type or device.

# Creating a tensor of type int32
x = torch.tensor([7.9, 8.99, 3.6], dtype=torch.int32)

# Using to() to change the data type to float32
x_float = x.to(torch.float32)

print(x_float)

tensor([7., 8., 3.])


| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [30]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [31]:
# addition: Adds 2 to each element of the tensor
print(x + 2)

# subtraction: Subtracts 2 from each element of the tensor
print(x - 2)

# multiplication: Multiplies each element by 3
print(x * 3)

# division: Divides each element by 3 (returns float)
print(x / 3)

# integer division: Multiplies by 100, then performs integer division by 3
print((x * 100) // 3)

# mod: Computes the remainder when performing integer division by 3, then takes mod 2
print(((x * 100) // 3) % 2)

# power: Raises each element to the power of 2
print(x ** 2)

# Note: Operations are element-wise on the tensor.


tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])
tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])
tensor([[23., 26.],
        [13., 30.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


### 2. Element wise operation

In [32]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [33]:
# add: Adds tensors a and b element-wise
a + b

# sub: Subtracts tensor b from tensor a element-wise
a - b

# multiply: Multiplies tensors a and b element-wise
a * b

# division: Divides tensor a by tensor b element-wise (returns float)
a / b

# power: Raises tensor a to the power of tensor b element-wise
a ** b

# mod: Computes the remainder when dividing tensor a by tensor b element-wise
a % b

# Note: Operations are element-wise between tensors a and b.


tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [34]:
c = torch.tensor([1, -2, 3, -4])

In [35]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [36]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [37]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [39]:
# round: Rounds each element of tensor d to the nearest integer.

torch.round(d)

tensor([2., 2., 4., 4.])

In [40]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [41]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [42]:
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [44]:
# clamp: Clamps each element of a tensor  to be within the specified range [min, max].

torch.clamp(d, min=2, max=3)

# Note: Values less than 2 are set to 2, and values greater than 3 are set to 3, keeping the rest unchanged.


tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [45]:
# randint: Creates a tensor with random integers in the specified range [low, high).

e = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)

# Note: Generates a tensor of shape (2, 3) with random integers between 0 and 9, then casts them to float32.
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [46]:
# sum: Computes the sum of all elements in tensor e
torch.sum(e)

# sum along columns: Computes the sum of elements along each column (dim=0)
torch.sum(e, dim=0)

# sum along rows: Computes the sum of elements along each row (dim=1)
torch.sum(e, dim=1)

# Note: Sum is computed along the specified dimension (0 for columns, 1 for rows).


tensor([15.,  9.])

In [47]:
# mean: Computes the mean of all elements in tensor e
torch.mean(e)

# mean along columns: Computes the mean of elements along each column (dim=0)
torch.mean(e, dim=0)

# Note: Mean is computed along the specified dimension (0 for columns).


tensor([4., 0., 8.])

In [49]:
# median: Computes the median of all elements in tensor e. The tensor must be of float type.

torch.median(e)


tensor(0.)

In [54]:
e = torch.rand(2,3)
e

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [55]:
# max: Computes the maximum value of all elements in tensor e
torch.max(e)

# min: Computes the minimum value of all elements in tensor e
torch.min(e)


tensor(0.0359)

In [56]:
# prod: Computes the product of all elements in tensor e
torch.prod(e)


tensor(0.0007)

In [57]:
# std: Computes the standard deviation of all elements in tensor e
torch.std(e)


tensor(0.2160)

In [58]:
# variance
torch.var(e)

tensor(0.0466)

In [59]:
e

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [61]:
# argmax: Returns the index of the maximum value in the flattened tensor
torch.argmax(e)

# Example: If The flattened view of a 2D tensor is [8, 7, 6, 9, 1, 8], argmax will give the maximum value (9) is at index 3.

tensor(2)

In [62]:
# argmin
torch.argmin(e) # position of the min val

tensor(1)

### 4. Matrix operations

In [63]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [64]:
# matmul: Performs matrix multiplication between tensors f and g
torch.matmul(f, g)

tensor([[137, 117],
        [139, 130]])

In [65]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot: Computes the dot product of two 1D tensors (vectors)
torch.dot(vector1, vector2)

tensor(11)

In [66]:
f

tensor([[5, 9, 8],
        [9, 7, 9]])

In [67]:
# transpose: Transposes the dimensions of tensor f, swapping dimension 0 (columns) with dimension 1 (rows)
torch.transpose(f, 0, 1)


tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [68]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 1., 5.],
        [5., 0., 4.],
        [3., 8., 8.]])

In [69]:
# det: Computes the determinant of a square matrix h
torch.det(h)


tensor(-20.0000)

In [70]:
# inverse: Computes the inverse of a square matrix h
torch.inverse(h)


tensor([[ 1.6000, -1.6000, -0.2000],
        [ 1.4000, -1.6500, -0.0500],
        [-2.0000,  2.2500,  0.2500]])

### 5. Comparison operations

In [71]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 3, 5],
        [0, 6, 4]])
tensor([[0, 8, 4],
        [7, 2, 3]])


In [72]:
# greater than: Checks if elements in i are greater than corresponding elements in j
i > j

# less than: Checks if elements in i are less than corresponding elements in j
i < j

# equal to: Checks if elements in i are equal to corresponding elements in j
i == j

# not equal to: Checks if elements in i are not equal to corresponding elements in j
i != j

# greater than or equal to: Checks if elements in i are greater than or equal to corresponding elements in j
i >= j

# less than or equal to: Checks if elements in i are less than or equal to corresponding elements in j
i <= j


tensor([[False,  True, False],
        [ True, False, False]])

### 6. Special functions

In [73]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[8., 5., 6.],
        [2., 9., 5.]])

In [74]:
# log: Computes the natural logarithm of each element in tensor k
torch.log(k)


tensor([[2.0794, 1.6094, 1.7918],
        [0.6931, 2.1972, 1.6094]])

In [75]:
# exp: Computes the exponential (e^x) of each element in tensor k
torch.exp(k)


tensor([[2.9810e+03, 1.4841e+02, 4.0343e+02],
        [7.3891e+00, 8.1031e+03, 1.4841e+02]])

In [76]:
# sqrt: Computes the square root of each element in tensor k
torch.sqrt(k)


tensor([[2.8284, 2.2361, 2.4495],
        [1.4142, 3.0000, 2.2361]])

In [77]:
# sigmoid: Applies the sigmoid activation function to each element in tensor k
torch.sigmoid(k)


tensor([[0.9997, 0.9933, 0.9975],
        [0.8808, 0.9999, 0.9933]])

In [78]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9975, 0.0180, 0.7311],
        [0.0025, 0.9820, 0.2689]])

In [79]:
# relu
torch.relu(k)

tensor([[8., 5., 6.],
        [2., 9., 5.]])

## Inplace Operations

In [80]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])
tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])


In [81]:
m.add(n) # this will create a new tensor , which might waste memory

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [82]:
# add_: Adds tensor n to tensor m in place, modifying m directly
m.add_(n)

# Note: The underscore (_) indicates an in-place operation, meaning the result is stored in tensor m itself.


tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [83]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [84]:
n

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [85]:
torch.relu(m)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [86]:
m.relu_() # will store the value in the m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [87]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

## Copying a Tensor

In [88]:
a = torch.rand(2,3)
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [89]:
b = a # this wont work , because b and a will point to same memory loc, change in a will also be in b

In [90]:
print(id(b))
print(id(a))

134290764000976
134290764000976


In [91]:
# clone: Creates a copy of tensor a and stores it in tensor b
b = a.clone()

# Note: .clone() is used to create a deep copy of the tensor, preserving the original tensor a.


In [92]:
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [93]:
b

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [94]:
a[0][0] = 10

In [95]:
a

tensor([[10.0000,  0.2131,  0.3957],
        [ 0.6017,  0.4234,  0.5224]])

In [96]:
b

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [97]:
id(a)

134290764000976

In [98]:
id(b)

134290764001360

### Tensor Operations on GPU :

In [3]:
# device: Specifies the device (CUDA GPU) for tensor operations
device = torch.device('cuda')

# Note: 'cuda' refers to the GPU device, allowing operations to be performed on the GPU.

In [4]:
# creating a new tensor on GPU :

torch.rand((2,3),device=device)

tensor([[0.6481, 0.1049, 0.9670],
        [0.7654, 0.7882, 0.9910]], device='cuda:0')

In [5]:
a = torch.rand((2,3))
a

tensor([[0.1924, 0.5041, 0.8661],
        [0.1753, 0.5761, 0.7264]])

In [6]:
# moving an existing tensor to GPU :
b = a.to(device)
b

tensor([[0.1924, 0.5041, 0.8661],
        [0.1753, 0.5761, 0.7264]], device='cuda:0')

In [7]:
# now all operations on b will be on GPU :

b+7

tensor([[7.1924, 7.5041, 7.8661],
        [7.1753, 7.5761, 7.7264]], device='cuda:0')

### Benefits of Performing Tensor Operations on a GPU:  
1. **Parallel Processing:** GPUs have thousands of cores optimized for parallel execution, making tensor computations significantly faster.  
2. **High Throughput:** GPUs can handle large-scale matrix and tensor operations simultaneously, improving performance in deep learning and scientific computing.  
3. **Optimized Libraries:** Libraries like CUDA, cuDNN, and TensorFlow leverage GPU acceleration for efficient tensor operations.  
4. **Reduced CPU Load:** Offloading tensor operations to a GPU frees up the CPU for other tasks, enhancing overall system efficiency.  
5. **Memory Bandwidth:** GPUs have high memory bandwidth, allowing faster data transfer and processing for large datasets.  
6. **Scalability:** GPUs support distributed computing, enabling scaling across multiple devices for increased performance.  
7. **Lower Latency for AI Tasks:** Deep learning models benefit from lower latency during training and inference, improving real-time applications.

In [14]:
import torch
import time

# Define matrix size
size = 1000  # Large matrix for better comparison

# Create two random matrices
A = torch.randn(size, size)
B = torch.randn(size, size)

# Perform operation on CPU
start_cpu = time.time()
C_cpu = torch.matmul(A, B)  # Matrix multiplication on CPU
end_cpu = time.time()
cpu_time = end_cpu - start_cpu

# Move tensors to GPU
A_gpu = A.to("cuda")
B_gpu = B.to("cuda")

# Perform operation on GPU
start_gpu = time.time()
C_gpu = torch.matmul(A_gpu, B_gpu)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure operation completes before measuring time
end_gpu = time.time()
gpu_time = end_gpu - start_gpu

# Print results
print(f"CPU Time: {cpu_time:.6f} sec")
print(f"GPU Time: {gpu_time:.6f} sec")
print(f"Speedup: {cpu_time / gpu_time:.2f} times faster ! ")

CPU Time: 0.017822 sec
GPU Time: 0.000964 sec
Speedup: 18.48 times faster ! 


### Reshaping Tensors :

In [8]:
a = torch.rand(4,4)
a

tensor([[0.9710, 0.4317, 0.7493, 0.0796],
        [0.2866, 0.6961, 0.8630, 0.4532],
        [0.6028, 0.5544, 0.8733, 0.3295],
        [0.2327, 0.7370, 0.9360, 0.6394]])

In [9]:
# reshape: Reshapes tensor a to the new shape (8, 2)
a.reshape(8, 2)


tensor([[0.9710, 0.4317],
        [0.7493, 0.0796],
        [0.2866, 0.6961],
        [0.8630, 0.4532],
        [0.6028, 0.5544],
        [0.8733, 0.3295],
        [0.2327, 0.7370],
        [0.9360, 0.6394]])

In [10]:
a.reshape(2,2,2,2)

tensor([[[[0.9710, 0.4317],
          [0.7493, 0.0796]],

         [[0.2866, 0.6961],
          [0.8630, 0.4532]]],


        [[[0.6028, 0.5544],
          [0.8733, 0.3295]],

         [[0.2327, 0.7370],
          [0.9360, 0.6394]]]])

In [40]:
# flatten() converts a multi-dimensional tensor into a 1D tensor while preserving the order of elements.
a.flatten()

tensor([0.5147, 0.1202, 0.0508, 0.7234, 0.2742, 0.5891, 0.5385, 0.4060, 0.7700,
        0.5564, 0.7768, 0.9418, 0.1319, 0.9462, 0.3954, 0.7353])

In [38]:
# permute() rearranges the dimensions of a tensor in the specified order without changing its data.

# Creating a tensor of shape (3, 4, 5)
b = torch.randn(3, 4, 5)

# Example:
# Imagine you have a tensor of shape (3,4,5), which represents:
# 3 -> Channels (like RGB)
# 4 -> Height
# 5 -> Width

# Applying permute(2,1,0):
# - Moves dim 2 (Width, 5) to the front
# - Keeps dim 1 (Height, 4) in place
# - Moves dim 0 (Channels, 3) to the last position
# New shape: (5,4,3)
permuted_b = b.permute(2, 1, 0)

# Printing shapes
print("Original shape:", b.shape)        # torch.Size([3, 4, 5])
print("Permuted shape:", permuted_b.shape) # torch.Size([5, 4, 3])


Original shape: torch.Size([3, 4, 5])
Permuted shape: torch.Size([5, 4, 3])


In [42]:
# unsqueeze() adds a new dimension at the specified position without changing the data.

# Creating a tensor of shape (2, 3)
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# Example:
# Imagine you have a tensor of shape (2,3), representing:
# 2 -> Rows
# 3 -> Columns

# Applying unsqueeze(0): Adds a new dimension at position 0
# New shape: (1, 2, 3)
a_unsqueeze_0 = a.unsqueeze(0)

# Applying unsqueeze(1): Adds a new dimension at position 1
# New shape: (2, 1, 3)
a_unsqueeze_1 = a.unsqueeze(1)

# Printing shapes
print("Original shape:", a.shape)              # torch.Size([2, 3])
print("After unsqueeze(0):", a_unsqueeze_0.shape) # torch.Size([1, 2, 3])
print("After unsqueeze(1):", a_unsqueeze_1.shape) # torch.Size([2, 1, 3])

Original shape: torch.Size([2, 3])
After unsqueeze(0): torch.Size([1, 2, 3])
After unsqueeze(1): torch.Size([2, 1, 3])


In [4]:
# squeeze() removes dimensions of size 1 from the tensor.

# Creating a tensor of shape (1, 3, 1, 4)
a = torch.tensor([[[[1, 2, 3, 4]]], [[[5, 6, 7, 8]]]])

# Example:
# Imagine you have a tensor of shape (1, 3, 1, 4), which represents:
# 1 -> Batch size or a single sample
# 3 -> Channels or depth (e.g., RGB channels)
# 1 -> A dimension with size 1 (could be a redundant dimension)
# 4 -> Number of features (e.g., pixel values)

# Applying squeeze(): Removes dimensions of size 1
# New shape: (3, 4)
a_squeezed = a.squeeze()

# Printing shapes
print("Original shape:", a.shape)          # torch.Size([1, 3, 1, 4])
print("After squeeze():", a_squeezed.shape) # torch.Size([3, 4])


Original shape: torch.Size([2, 1, 1, 4])
After squeeze(): torch.Size([2, 4])


### Converting Between Numpy and Pytorch :

#### torch to numpy :

In [20]:
import numpy as np

In [21]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [22]:
# numpy: Converts tensor a to a NumPy array
b = a.numpy()


In [23]:
type(b)

numpy.ndarray

#### numpy to torch :

In [24]:
c = np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [25]:
# from_numpy: Converts a NumPy array c to a PyTorch tensor
d = torch.from_numpy(c)

Congratulations! You reached the bottom of the code. No prize, but you can take a deep breath and feel accomplished. 🎉